
CREATE PROCEDURE SP_LISTA_OPCIONES_USUARIO
/*
exec SP_LISTA_OPCIONES_USUARIO '70994785'
*/
(
@USUARIO VARCHAR(20)
)
AS BEGIN
	SELECT
	O.ID_OPCION
	,O.OPCION
	,O.CONTROLLER
	,O.ACCION
	FROM OPCION O
	INNER JOIN OPCION_ROL OPR ON O.ID_OPCION = OPR.ID_OPCION
	INNER JOIN ROL R ON OPR.ID_ROL = R.ID_ROL
	INNER JOIN USUARIO_ROL UR ON R.ID_ROL = UR.ID_ROL
	INNER JOIN USUARIO U ON UR.ID_USUARIO = U.ID_USUARIO
	WHERE U.DNI = @USUARIO
END