--CREATE DATABASE BD_APPSICO

--USE BD_APPSICO

CREATE TABLE OPCION
(
ID_OPCION INT IDENTITY(1,1) PRIMARY KEY
,OPCION VARCHAR(120)
,CONTROLLER VARCHAR(120)
,ACCION VARCHAR(120)
)

INSERT INTO OPCION VALUES
('Opciones','Opciones','Index')

CREATE TABLE ROL
(
ID_ROL INT IDENTITY (1,1) PRIMARY KEY
,NOMBRE_ROL VARCHAR(250)
)

INSERT INTO ROL VALUES
('ADMINISTRADOR'),
('CLIENTE'),
('PSICOLOGO'),
('COLABORADOR')

SELECT * FROM OPCION
SELECT * FROM ROL

CREATE TABLE OPCION_ROL
(
ID_OPCION_ROL INT IDENTITY(1,1) PRIMARY KEY
,ID_OPCION INT FOREIGN KEY REFERENCES OPCION
,ID_ROL INT FOREIGN KEY REFERENCES ROL
)

INSERT INTO OPCION_ROL VALUES
(1,1)

CREATE TABLE USUARIO
(
ID_USUARIO INT IDENTITY(1,1) PRIMARY KEY
,DNI VARCHAR(250)
,CONTRASEÑA VARCHAR(250)
,FECHA_REGISTRO DATETIME
,ESTADO BIT
)

INSERT INTO USUARIO VALUES
('70994785','123456',GETDATE(),1)

CREATE TABLE USUARIO_ROL
(
ID_USUARIO_ROL INT IDENTITY(1,1) PRIMARY KEY
,ID_USUARIO INT FOREIGN KEY REFERENCES USUARIO
,ID_ROL INT FOREIGN KEY REFERENCES ROL
)

INSERT INTO USUARIO_ROL VALUES
(1,1)

CREATE TABLE CLIENTE
(
ID_CLIENTE INT IDENTITY(1,1) PRIMARY KEY
,NOMBRE_COMPLETO VARCHAR(250)
,TIPO_DOCUM VARCHAR(3)
,NUM_DOCUM VARCHAR(15)
,CORREO VARCHAR(250)
,TELEFONO VARCHAR(15)
,FECHA_NACIMIENTO DATETIME
,GENERO VARCHAR(1)
,ESTADO BIT
)

CREATE TABLE PSICOLOGO
(
ID_PSICOLOGO INT IDENTITY(1,1) PRIMARY KEY
,NOMBRE_COMPLETO VARCHAR(250)
,TIPO_DOCUM VARCHAR(3)
,NUM_DOCUM VARCHAR(15)
,CORREO VARCHAR(250)
,TELEFONO VARCHAR(15)
,FECHA_NACIMIENTO DATETIME
,GENERO VARCHAR(1)
,ESTADO BIT
)

CREATE TABLE SERVICIO
(
ID_SERVICIO INT IDENTITY(1,1) PRIMARY KEY
,SERVICIO VARCHAR(250)
,PRECIO DECIMAL(18,2)
,ESTADO BIT
)


CREATE TABLE PSICOLOGO_SERVICIO
(
ID_PSICOLOGO_SERVICIO INT IDENTITY(1,1) PRIMARY KEY
,ID_PSICOLOGO INT FOREIGN KEY REFERENCES PSICOLOGO
,ID_SERVICIO INT FOREIGN KEY REFERENCES SERVICIO
)

CREATE TABLE HORARIO
(
ID_HORARIO INT IDENTITY(1,1) PRIMARY KEY
,HORARIO VARCHAR(50)
,COD_HORARIO VARCHAR(5)
,HORA_INICIO TIME
,HORA_FIN TIME
,ESTADO BIT
)

INSERT INTO HORARIO VALUES
('L-S Full Time', 'L-S','09:00:00.00','18:00:00.00',1),
('L-S Part Time Mañana', 'L-S','09:00:00.00','13:00:00.00',1),
('L-S Part Time Tarde', 'L-S','14:00:00.00','18:00:00.00',1),
('L-V Full Time', 'L-V','09:00:00.00','18:00:00.00',1),
('L-S Part Time Mañana', 'L-V','09:00:00.00','13:00:00.00',1),
('L-S Part Time Tarde', 'L-V','14:00:00.00','18:00:00.00',1)

CREATE TABLE PSICOLOGO_HORARIO
(
ID_PSICOLOGO_HORARIO INT IDENTITY(1,1) PRIMARY KEY
,ID_PSICOLOGO INT FOREIGN KEY REFERENCES PSICOLOGO
,ID_HORARIO INT FOREIGN KEY REFERENCES HORARIO
)

CREATE TABLE COLABORADOR
(
ID_COLABORADOR INT IDENTITY(1,1) PRIMARY KEY
,NOMBRE_COMPLETO VARCHAR(250)
,TIPO_DOCUM VARCHAR(3)
,NUM_DOCUM VARCHAR(15)
,CORREO VARCHAR(250)
,TELEFONO VARCHAR(15)
,FECHA_NACIMIENTO DATETIME
,GENERO VARCHAR(1)
,ESTADO BIT
)

CREATE TABLE CITAS
(
ID_CITAS INT IDENTITY(1,1) PRIMARY KEY
,ID_CLIENTE INT FOREIGN KEY REFERENCES CLIENTE
,ID_SERVICIO INT FOREIGN KEY REFERENCES SERVICIO
,ID_PSICOLOGO INT FOREIGN KEY REFERENCES PSICOLOGO
,ID_COLABORADOR INT FOREIGN KEY REFERENCES COLABORADOR
,FECHA_CITA DATETIME
,HORA_INICIO DATETIME
,HORA_FIN DATETIME
,OBSERVACION VARCHAR(MAX)
,ESTADO VARCHAR(20) -- PROGRAMADA - CANCELADA - COMPLETADA
)

CREATE TABLE ARCHIVOS_CITAS
(
ID_ARCHIVOS_CITAS INT IDENTITY(1,1) PRIMARY KEY
,ID_CITAS INT FOREIGN KEY REFERENCES CITAS
,NOMBRE_FILE VARCHAR(250)
,ARCHIVO VARCHAR(MAX)
)

CREATE TABLE HISTORIAL_CITAS
(
ID_HISTORIAL_CITAS INT IDENTITY(1,1) PRIMARY KEY
,ID_CITAS INT FOREIGN KEY REFERENCES CITAS
,OBSERVACION VARCHAR(MAX)
)

SELECT * FROM OPCION
SELECT * FROM ROL
SELECT * FROM OPCION_ROL
SELECT * FROM USUARIO
SELECT * FROM USUARIO_ROL
SELECT * FROM CLIENTE
SELECT * FROM PSICOLOGO
SELECT * FROM SERVICIO
SELECT * FROM PSICOLOGO_SERVICIO
SELECT * FROM HORARIO
SELECT * FROM PSICOLOGO_HORARIO
SELECT * FROM COLABORADOR
SELECT * FROM CITAS
SELECT * FROM ARCHIVOS_CITAS
SELECT * FROM HISTORIAL_CITAS
